// Code generated by protoc-gen-gogo.
// source: prototest.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	prototest.proto

It has these top-level messages:
	TestMessage
*/
package main

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type TestMessage_ItemType int32

const (
	TestMessage_TypeX TestMessage_ItemType = 0
	TestMessage_TypeY TestMessage_ItemType = 1
	TestMessage_TypeZ TestMessage_ItemType = 2
)

var TestMessage_ItemType_name = map[int32]string{
	0: "TypeX",
	1: "TypeY",
	2: "TypeZ",
}
var TestMessage_ItemType_value = map[string]int32{
	"TypeX": 0,
	"TypeY": 1,
	"TypeZ": 2,
}

func (x TestMessage_ItemType) Enum() *TestMessage_ItemType {
	p := new(TestMessage_ItemType)
	*p = x
	return p
}
func (x TestMessage_ItemType) String() string {
	return proto.EnumName(TestMessage_ItemType_name, int32(x))
}
func (x *TestMessage_ItemType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TestMessage_ItemType_value, data, "TestMessage_ItemType")
	if err != nil {
		return err
	}
	*x = TestMessage_ItemType(value)
	return nil
}
func (TestMessage_ItemType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorPrototest, []int{0, 0}
}

type TestMessage struct {
	ClientName       string                `protobuf:"bytes,1,req,name=clientName" json:"clientName"`
	ClientId         int32                 `protobuf:"varint,2,req,name=clientId" json:"clientId"`
	Description      string                `protobuf:"bytes,3,opt,name=description" json:"description"`
	Messageitems     []TestMessage_MsgItem `protobuf:"bytes,4,rep,name=messageitems" json:"messageitems"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *TestMessage) Reset()                    { *m = TestMessage{} }
func (m *TestMessage) String() string            { return proto.CompactTextString(m) }
func (*TestMessage) ProtoMessage()               {}
func (*TestMessage) Descriptor() ([]byte, []int) { return fileDescriptorPrototest, []int{0} }

func (m *TestMessage) GetClientName() string {
	if m != nil {
		return m.ClientName
	}
	return ""
}

func (m *TestMessage) GetClientId() int32 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

func (m *TestMessage) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *TestMessage) GetMessageitems() []TestMessage_MsgItem {
	if m != nil {
		return m.Messageitems
	}
	return nil
}

type TestMessage_MsgItem struct {
	Id               int32                `protobuf:"varint,1,req,name=id" json:"id"`
	ItemName         string               `protobuf:"bytes,2,opt,name=itemName" json:"itemName"`
	ItemValue        int32                `protobuf:"varint,3,opt,name=itemValue" json:"itemValue"`
	ItemType         TestMessage_ItemType `protobuf:"varint,4,opt,name=itemType,enum=main.TestMessage_ItemType" json:"itemType"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *TestMessage_MsgItem) Reset()                    { *m = TestMessage_MsgItem{} }
func (m *TestMessage_MsgItem) String() string            { return proto.CompactTextString(m) }
func (*TestMessage_MsgItem) ProtoMessage()               {}
func (*TestMessage_MsgItem) Descriptor() ([]byte, []int) { return fileDescriptorPrototest, []int{0, 0} }

func (m *TestMessage_MsgItem) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TestMessage_MsgItem) GetItemName() string {
	if m != nil {
		return m.ItemName
	}
	return ""
}

func (m *TestMessage_MsgItem) GetItemValue() int32 {
	if m != nil {
		return m.ItemValue
	}
	return 0
}

func (m *TestMessage_MsgItem) GetItemType() TestMessage_ItemType {
	if m != nil {
		return m.ItemType
	}
	return TestMessage_TypeX
}

func init() {
	proto.RegisterType((*TestMessage)(nil), "main.TestMessage")
	proto.RegisterType((*TestMessage_MsgItem)(nil), "main.TestMessage.MsgItem")
	proto.RegisterEnum("main.TestMessage_ItemType", TestMessage_ItemType_name, TestMessage_ItemType_value)
}

func init() { proto.RegisterFile("prototest.proto", fileDescriptorPrototest) }

var fileDescriptorPrototest = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x8f, 0xcf, 0x4e, 0x84, 0x30,
	0x10, 0xc6, 0x97, 0x3f, 0x1b, 0x97, 0xc1, 0x28, 0x69, 0x3c, 0x20, 0x17, 0x09, 0x31, 0x86, 0xc4,
	0xc8, 0x26, 0x7b, 0xf6, 0xa4, 0x27, 0x0e, 0xeb, 0xc1, 0x6c, 0x8c, 0x7a, 0x63, 0xa1, 0x62, 0x93,
	0x85, 0x92, 0x6d, 0x39, 0xf8, 0x20, 0x3e, 0x81, 0x2f, 0xe3, 0x53, 0xf8, 0x2c, 0xb6, 0x85, 0x62,
	0xcd, 0x9e, 0xfa, 0x7d, 0x33, 0xdf, 0x4c, 0x7f, 0x03, 0xa7, 0xdd, 0x9e, 0x72, 0xca, 0x31, 0xe3,
	0x99, 0x52, 0xc8, 0x6d, 0x0a, 0xd2, 0x46, 0x37, 0x35, 0xe1, 0xef, 0xfd, 0x36, 0x2b, 0x69, 0xb3,
	0xac, 0x69, 0x4d, 0x97, 0xaa, 0xb9, 0xed, 0xdf, 0x94, 0x53, 0x46, 0xa9, 0x61, 0x28, 0xf9, 0x74,
	0xc0, 0xdf, 0x88, 0x1d, 0x6b, 0xcc, 0x58, 0x51, 0x63, 0x74, 0x09, 0x50, 0xee, 0x08, 0x6e, 0xf9,
	0x43, 0xd1, 0xe0, 0xd0, 0x8a, 0xed, 0xd4, 0xbb, 0x73, 0xbf, 0x7f, 0x2e, 0x66, 0x8f, 0x46, 0x1d,
	0xc5, 0xb0, 0x18, 0x5c, 0x5e, 0x85, 0xb6, 0xc8, 0xcc, 0xc7, 0xcc, 0x54, 0x45, 0x57, 0xe0, 0x57,
	0x98, 0x95, 0x7b, 0xd2, 0x71, 0x42, 0xdb, 0xd0, 0x89, 0xad, 0x69, 0x91, 0xd9, 0x40, 0xf7, 0x70,
	0xdc, 0x0c, 0x5f, 0x13, 0x8e, 0x1b, 0x16, 0xba, 0xb1, 0x93, 0xfa, 0xab, 0xf3, 0x4c, 0xde, 0x92,
	0x19, 0x60, 0xd9, 0x9a, 0xd5, 0xb9, 0x48, 0x8c, 0x3b, 0xfe, 0x0d, 0x45, 0x5f, 0x16, 0x1c, 0x8d,
	0x7d, 0x74, 0x06, 0x36, 0xa9, 0x14, 0xb8, 0x86, 0x12, 0x5e, 0x02, 0xcb, 0xa8, 0x3a, 0xca, 0x36,
	0x58, 0xa6, 0x2a, 0x4a, 0xc0, 0x93, 0xfa, 0xa9, 0xd8, 0xf5, 0x58, 0xe1, 0xea, 0xf1, 0xbf, 0x32,
	0xba, 0x1d, 0xb6, 0x6c, 0x3e, 0x3a, 0x2c, 0x40, 0xad, 0xf4, 0x64, 0x15, 0x1d, 0x82, 0xe6, 0x63,
	0xc2, 0xfc, 0x41, 0xfa, 0xe4, 0x1a, 0x16, 0xba, 0x87, 0x3c, 0x98, 0xcb, 0xf7, 0x39, 0x98, 0x69,
	0xf9, 0x12, 0x58, 0x5a, 0xbe, 0x06, 0xf6, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2f, 0xd4, 0x5b,
	0xa7, 0xde, 0x01, 0x00, 0x00,
}
